[
  {
    "id": 101,
    "name": "Creatine Monohydrate",
    "slug": "creatine-monohydrate",
    "category": "Physical Performance",
    "primaryGoal": "Strength and Mass Gain",
    "description": "The most studied supplement in the world for improving anaerobic performance, maximal strength, and muscle hydration.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "3-5g per day",
    "timing": "Any time",
    "tags": ["Strength", "Muscle Mass", "Recovery", "Energy"],
    "warnings": ["Drink plenty of water"],
    "imageUrl": "images/creatine.jpg"
  },
  {
    "id": 102,
    "name": "Caffeine Anhydrous",
    "slug": "caffeine-anhydrous",
    "category": "Stimulants",
    "primaryGoal": "Energy and Focus",
    "description": "Powerful central nervous system stimulant. Reduces the perception of fatigue and improves concentration.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "100-200mg",
    "timing": "30 min pre-workout",
    "tags": ["Energy", "Focus", "Metabolism", "Endurance"],
    "warnings": ["Can cause insomnia", "Watch for tolerance build-up"],
    "imageUrl": "images/caffeine.jpg"
  },
  {
    "id": 103,
    "name": "Ashwagandha (KSM-66)",
    "slug": "ashwagandha",
    "category": "Adaptogens",
    "primaryGoal": "Stress Reduction",
    "description": "Adaptogenic herb used to lower cortisol levels and improve resilience to physical and mental stress.",
    "evidenceLevel": "B",
    "evidenceLabel": "High",
    "dosage": "300-600mg",
    "timing": "Breakfast or Dinner",
    "tags": ["Stress", "Anxiety", "Sleep", "Testosterone"],
    "warnings": ["Possible drowsiness"],
    "imageUrl": "images/ashwagandha.jpg"
  },
  {
    "id": 104,
    "name": "Magnesium Bisglycinate",
    "slug": "magnesium-bisglycinate",
    "category": "Minerals",
    "primaryGoal": "Sleep and Relaxation",
    "description": "High-absorption form of magnesium that promotes muscle relaxation and improves deep sleep quality.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "200-400mg",
    "timing": "30 min before bed",
    "tags": ["Sleep", "Recovery", "Nervous System", "Cramps"],
    "warnings": [],
    "imageUrl": "images/magnesium.jpg"
  },
  {
    "id": 105,
    "name": "L-Theanine",
    "slug": "l-theanine",
    "category": "Nootropics",
    "primaryGoal": "Relaxation without Drowsiness",
    "description": "Amino acid found in green tea. Often used in combination with caffeine to mitigate side effects (jitters).",
    "evidenceLevel": "B",
    "evidenceLabel": "High",
    "dosage": "100-200mg",
    "timing": "With caffeine",
    "tags": ["Focus", "Calm", "Anxiety"],
    "warnings": [],
    "imageUrl": "images/l-theanine.jpg"
  },
  {
    "id": 106,
    "name": "Omega-3 (Fish Oil)",
    "slug": "omega-3",
    "category": "General Health",
    "primaryGoal": "Cardiovascular and Brain Health",
    "description": "Essential fatty acids (EPA and DHA) crucial for reducing systemic inflammation and supporting cognitive function.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "1-2g total EPA/DHA",
    "timing": "With meals",
    "tags": ["Heart", "Brain", "Inflammation", "Skin"],
    "warnings": ["Check product oxidation"],
    "imageUrl": "images/omega3.jpg"
  },
  {
    "id": 107,
    "name": "Melatonin",
    "slug": "melatonin",
    "category": "Sleep",
    "primaryGoal": "Circadian Rhythm Regulation",
    "description": "Natural hormone that signals the body it is time to sleep. Effective for jet lag and reducing time to fall asleep.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "0.5-3mg",
    "timing": "60 min before bed",
    "tags": ["Sleep", "Jet Lag"],
    "warnings": ["Do not use long-term without consultation"],
    "imageUrl": "images/melatonin.jpg"
  },
  {
    "id": 108,
    "name": "Tribulus Terrestris",
    "slug": "tribulus",
    "category": "Libido",
    "primaryGoal": "Libido Enhancement",
    "description": "Often sold as a testosterone booster, but scientific evidence supports only an effect on libido, not hormones.",
    "evidenceLevel": "C",
    "evidenceLabel": "Low/Controversial",
    "dosage": "500-1000mg",
    "timing": "Morning",
    "tags": ["Libido", "Energy"],
    "warnings": ["Dubious efficacy on muscle mass"],
    "imageUrl": "images/tribulus.jpg"
  },
  {
    "id": 109,
    "name": "Vitamin D3",
    "slug": "vitamin-d3",
    "category": "General Health",
    "primaryGoal": "Immune and Bone Support",
    "description": "Crucial for those spending time indoors. Regulates mood, immune system, and bone health.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "1000-5000 IU (based on deficiency)",
    "timing": "With meals containing fat",
    "tags": ["Immunity", "Bones", "Mood", "Hormones"],
    "warnings": ["Monitor blood levels"],
    "imageUrl": "images/vitamind.jpg"
  },
  {
    "id": 110,
    "name": "Beta-Alanine",
    "slug": "beta-alanine",
    "category": "Physical Performance",
    "primaryGoal": "Muscle Endurance",
    "description": "Helps buffer lactic acid in muscles. Useful for high-intensity efforts lasting between 1 and 4 minutes.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "2-5g",
    "timing": "Pre-workout",
    "tags": ["Endurance", "Performance", "Fatigue"],
    "warnings": ["Paresthesia (harmless tingling)"],
    "imageUrl": "images/betaalanine.jpg"
  },
  {
    "id": 111,
    "name": "Whey Protein",
    "slug": "whey-protein",
    "category": "Physical Performance",
    "primaryGoal": "Muscle Recovery and Growth",
    "description": "Fast-absorbing milk protein essential for stimulating muscle protein synthesis post-workout.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "20-40g",
    "timing": "Post-workout or as a snack",
    "tags": ["Muscle", "Recovery", "Protein"],
    "warnings": ["Contains lactose (unless Isolate)"],
    "imageUrl": "images/whey.jpg"
  },
  {
    "id": 112,
    "name": "Citrulline Malate",
    "slug": "citrulline-malate",
    "category": "Physical Performance",
    "primaryGoal": "Blood Flow and Pump",
    "description": "Increases nitric oxide production better than Arginine, improving blood flow, pumps, and reducing fatigue.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "6-8g",
    "timing": "30-60 min pre-workout",
    "tags": ["Pump", "Circulation", "Endurance"],
    "warnings": ["Sour taste"],
    "imageUrl": "images/citrulline.jpg"
  },
  {
    "id": 113,
    "name": "Zinc Picolinate",
    "slug": "zinc-picolinate",
    "category": "General Health",
    "primaryGoal": "Immunity and Hormonal Support",
    "description": "Essential mineral for immune function, DNA synthesis, and testosterone production.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "15-30mg",
    "timing": "With food",
    "tags": ["Immunity", "Testosterone", "Skin"],
    "warnings": ["Do not take on empty stomach (nausea)"],
    "imageUrl": "images/zinc.jpg"
  },
  {
    "id": 114,
    "name": "Curcumin (Turmeric)",
    "slug": "curcumin",
    "category": "General Health",
    "primaryGoal": "Anti-Inflammatory",
    "description": "Potent anti-inflammatory compound. Best absorbed when paired with Piperine (Black Pepper extract).",
    "evidenceLevel": "B",
    "evidenceLabel": "High",
    "dosage": "500-1500mg",
    "timing": "With meals",
    "tags": ["Joints", "Inflammation", "Digestion"],
    "warnings": ["Requires Piperine for absorption"],
    "imageUrl": "images/curcumin.jpg"
  },
  {
    "id": 115,
    "name": "Rhodiola Rosea",
    "slug": "rhodiola-rosea",
    "category": "Adaptogens",
    "primaryGoal": "Fatigue Reduction",
    "description": "Adaptogen that helps reduce perceived fatigue and exhaustion during prolonged stressful periods.",
    "evidenceLevel": "B",
    "evidenceLabel": "High",
    "dosage": "280-680mg",
    "timing": "Morning",
    "tags": ["Energy", "Focus", "Stress"],
    "warnings": [],
    "imageUrl": "images/rhodiola.jpg"
  },
  {
    "id": 116,
    "name": "Multivitamin",
    "slug": "multivitamin",
    "category": "General Health",
    "primaryGoal": "Nutritional Baseline",
    "description": "Blend of essential vitamins and minerals to prevent micronutrient deficiencies.",
    "evidenceLevel": "B",
    "evidenceLabel": "Variable",
    "dosage": "1 serving",
    "timing": "Breakfast",
    "tags": ["Wellness", "Health"],
    "warnings": ["Does not replace real food"],
    "imageUrl": "images/multivitamin.jpg"
  },
  {
    "id": 117,
    "name": "Collagen Peptides",
    "slug": "collagen",
    "category": "Beauty/Joints",
    "primaryGoal": "Skin and Joint Health",
    "description": "Supports skin elasticity and joint cartilage health. Works best when taken with Vitamin C.",
    "evidenceLevel": "B",
    "evidenceLabel": "Medium/High",
    "dosage": "10-20g",
    "timing": "Any time",
    "tags": ["Skin", "Joints", "Hair"],
    "warnings": ["Not a complete protein source"],
    "imageUrl": "images/collagen.jpg"
  },
  {
    "id": 118,
    "name": "Coenzyme Q10 (CoQ10)",
    "slug": "coq10",
    "category": "General Health",
    "primaryGoal": "Heart Health and Energy",
    "description": "Molecule involved in cellular energy production. Vital for heart health and mitochondrial function.",
    "evidenceLevel": "B",
    "evidenceLabel": "High",
    "dosage": "100-200mg",
    "timing": "With meals containing fat",
    "tags": ["Heart", "Mitochondria", "Aging"],
    "warnings": [],
    "imageUrl": "images/coq10.jpg"
  },
  {
    "id": 119,
    "name": "Glutamine",
    "slug": "glutamine",
    "category": "Gut Health",
    "primaryGoal": "Intestinal Health",
    "description": "While less effective for muscle building than once thought, it is excellent for gut lining repair and immunity.",
    "evidenceLevel": "B",
    "evidenceLabel": "Medium",
    "dosage": "5g",
    "timing": "Post-workout or before bed",
    "tags": ["Gut", "Immunity", "Recovery"],
    "warnings": [],
    "imageUrl": "images/glutamine.jpg"
  },
  {
    "id": 120,
    "name": "BCAAs",
    "slug": "bcaa",
    "category": "Physical Performance",
    "primaryGoal": "Muscle Preservation",
    "description": "Branched-chain amino acids (Leucine, Isoleucine, Valine). Useful mainly if training fasted.",
    "evidenceLevel": "C",
    "evidenceLabel": "Medium/Low",
    "dosage": "5-10g",
    "timing": "Intra-workout",
    "tags": ["Muscle", "Endurance"],
    "warnings": ["Redundant if protein intake is sufficient"],
    "imageUrl": "images/bcaa.jpg"
  },
  {
    "id": 121,
    "name": "Casein Protein",
    "slug": "casein",
    "category": "Physical Performance",
    "primaryGoal": "Sustained Protein Release",
    "description": "Slow-digesting milk protein that provides a steady stream of amino acids, ideal for overnight recovery.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "20-40g",
    "timing": "Before bed",
    "tags": ["Muscle", "Recovery", "Satiety"],
    "warnings": ["Contains lactose"],
    "imageUrl": "images/casein.jpg"
  },
  {
    "id": 122,
    "name": "Probiotics",
    "slug": "probiotics",
    "category": "Gut Health",
    "primaryGoal": "Microbiome Balance",
    "description": "Live bacteria strains intended to support a healthy gut microbiome, digestion, and immunity.",
    "evidenceLevel": "B",
    "evidenceLabel": "High (strain dependent)",
    "dosage": "10-50 Billion CFU",
    "timing": "Before first meal",
    "tags": ["Digestion", "Gut", "Immunity"],
    "warnings": ["Keep refrigerated if required"],
    "imageUrl": "images/probiotics.jpg"
  },
  {
    "id": 123,
    "name": "Vitamin C",
    "slug": "vitamin-c",
    "category": "General Health",
    "primaryGoal": "Antioxidant Support",
    "description": "Water-soluble vitamin essential for collagen synthesis and immune defense.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "500-1000mg",
    "timing": "Morning",
    "tags": ["Immunity", "Skin", "Antioxidant"],
    "warnings": ["High doses can cause loose stool"],
    "imageUrl": "images/vitaminc.jpg"
  },
  {
    "id": 124,
    "name": "NAC (N-Acetyl Cysteine)",
    "slug": "nac",
    "category": "General Health",
    "primaryGoal": "Liver Support and Antioxidant",
    "description": "Precursor to Glutathione, the body's master antioxidant. Protects the liver and clears mucus.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "600-1200mg",
    "timing": "Any time",
    "tags": ["Liver", "Detox", "Lungs"],
    "warnings": [],
    "imageUrl": "images/nac.jpg"
  },
  {
    "id": 125,
    "name": "Psyllium Husk",
    "slug": "psyllium-husk",
    "category": "Digestion",
    "primaryGoal": "Fiber Intake",
    "description": "Soluble fiber that aids regularity, feeds gut bacteria, and can help lower cholesterol.",
    "evidenceLevel": "A",
    "evidenceLabel": "Very High",
    "dosage": "5g",
    "timing": "With large glass of water",
    "tags": ["Digestion", "Heart", "Satiety"],
    "warnings": ["Must drink plenty of water"],
    "imageUrl": "images/psyllium.jpg"
  },
  {
    "id": 126,
    "name": "Lion's Mane Mushroom",
    "slug": "lions-mane",
    "category": "Nootropics",
    "primaryGoal": "Cognitive Function",
    "description": "Medicinal mushroom shown to stimulate Nerve Growth Factor (NGF) production and improve memory.",
    "evidenceLevel": "B",
    "evidenceLabel": "Medium",
    "dosage": "500-1000mg",
    "timing": "Morning",
    "tags": ["Brain", "Focus", "Memory"],
    "warnings": [],
    "imageUrl": "images/lionsmane.jpg"
  },
  {
    id: 127,
    name: "Iron Bisglycinate",
    slug: "iron-bisglycinate",
    category: "Minerals",
    primaryGoal: "Blood Health",
    description:
      "Essential for transporting oxygen in the blood. Bisglycinate form is gentle on the stomach and highly bioavailable.",
    evidenceLevel: "A",
    evidenceLabel: "Very High",
    dosage: "14-28mg",
    timing: "With Vitamin C, away from caffeine/calcium",
    tags: ["Energy", "Blood", "Women's Health"],
    warnings: ["Do not take if not deficient", "Keep away from children"],
    imageUrl: "images/iron.jpg",
  },
  {
    id: 128,
    name: "Vitamin B12 (Methylcobalamin)",
    slug: "vitamin-b12",
    category: "Vitamins",
    primaryGoal: "Energy and Nerve Health",
    description:
      "Crucial for nerve tissue health, brain function, and the production of red blood cells. Methylcobalamin is the active form.",
    evidenceLevel: "A",
    evidenceLabel: "Very High",
    dosage: "1000-5000mcg",
    timing: "Morning",
    tags: ["Energy", "Brain", "Vegan"],
    warnings: [],
    imageUrl: "images/vitaminb12.jpg",
  },
  {
    id: 129,
    name: "Vitamin K2 (MK-7)",
    slug: "vitamin-k2",
    category: "Vitamins",
    primaryGoal: "Bone and Heart Health",
    description:
      "Directs calcium into the bones and teeth and keeps it out of the arteries. Synergistic with Vitamin D3.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "100-200mcg",
    timing: "With meals containing fat",
    tags: ["Bones", "Heart", "Teeth"],
    warnings: ["Consult doctor if on blood thinners"],
    imageUrl: "images/vitamink2.jpg",
  },
  {
    id: 130,
    name: "L-Carnitine L-Tartrate",
    slug: "l-carnitine",
    category: "Physical Performance",
    primaryGoal: "Fat Metabolism and Recovery",
    description:
      "Helps transport fatty acids into mitochondria to be burned for energy. Also aids in androgen receptor density recovery.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "2-4g",
    timing: "Pre-workout or with carbohydrates",
    tags: ["Fat Loss", "Recovery", "Energy"],
    warnings: ["Fishy odor (rare)"],
    imageUrl: "images/lcarnitine.jpg",
  },
  {
    id: 131,
    name: "L-Tyrosine",
    slug: "l-tyrosine",
    category: "Nootropics",
    primaryGoal: "Focus Under Stress",
    description:
      "Precursor to dopamine and norepinephrine. Improves cognitive performance specifically during acute stressful situations.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "1-2g",
    timing: "30-60 min pre-stressor",
    tags: ["Focus", "Stress", "Dopamine"],
    warnings: ["Avoid if on MAOIs"],
    imageUrl: "images/tyrosine.jpg",
  },
  {
    id: 132,
    name: "Taurine",
    slug: "taurine",
    category: "General Health",
    primaryGoal: "Cellular Hydration and Calm",
    description:
      "Amino acid that supports hydration, heart health, and acts as a mild GABA agonist to reduce anxiety.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "1-3g",
    timing: "Any time or pre-workout",
    tags: ["Hydration", "Heart", "Calm", "Cramps"],
    warnings: [],
    imageUrl: "images/taurine.jpg",
  },
  {
    id: 133,
    name: "Glucosamine Sulfate",
    slug: "glucosamine",
    category: "Joints",
    primaryGoal: "Joint Health",
    description:
      "Compound found naturally in cartilage. Used to reduce joint pain and slow cartilage degradation.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "1500mg",
    timing: "With meals",
    tags: ["Joints", "Pain", "Arthritis"],
    warnings: ["Shellfish allergy risk"],
    imageUrl: "images/glucosamine.jpg",
  },
  {
    id: 134,
    name: "MSM (Methylsulfonylmethane)",
    slug: "msm",
    category: "Joints",
    primaryGoal: "Anti-Inflammatory",
    description:
      "Organic sulfur compound used to decrease joint inflammation and improve skin health.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "3g",
    timing: "With meals",
    tags: ["Joints", "Skin", "Inflammation"],
    warnings: [],
    imageUrl: "images/msm.jpg",
  },
  {
    id: 135,
    name: "Berberine",
    slug: "berberine",
    category: "General Health",
    primaryGoal: "Blood Sugar Control",
    description:
      "Plant alkaloid shown to be as effective as some pharmaceuticals in regulating blood glucose and improving insulin sensitivity.",
    evidenceLevel: "A",
    evidenceLabel: "Very High",
    dosage: "500mg (3x daily)",
    timing: "Before carbohydrate meals",
    tags: ["Glucose", "Insulin", "Metabolism"],
    warnings: ["Can cause stomach upset", "Interacts with enzymes"],
    imageUrl: "images/berberine.jpg",
  },
  {
    id: 136,
    name: "Maca Root",
    slug: "maca",
    category: "Libido",
    primaryGoal: "Libido and Energy",
    description:
      "Peruvian plant used to enhance libido and fertility. It does not directly increase testosterone but improves sexual well-being.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "1.5-3g",
    timing: "Morning",
    tags: ["Libido", "Energy", "Mood"],
    warnings: [],
    imageUrl: "images/maca.jpg",
  },
  {
    id: 137,
    name: "Panax Ginseng",
    slug: "panax-ginseng",
    category: "Adaptogens",
    primaryGoal: "Vitality and Cognition",
    description:
      "Traditional herb used to improve general well-being, physical stamina, and concentration.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "200-400mg",
    timing: "Morning",
    tags: ["Energy", "Focus", "Immunity"],
    warnings: [],
    imageUrl: "images/ginseng.jpg",
  },
  {
    id: 138,
    name: "Ginkgo Biloba",
    slug: "ginkgo-biloba",
    category: "Nootropics",
    primaryGoal: "Memory and Blood Flow",
    description:
      "Improves blood circulation to the brain, which may help with memory and cognitive speed.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "120-240mg",
    timing: "With meals",
    tags: ["Memory", "Circulation", "Brain"],
    warnings: ["Blood thinning effect"],
    imageUrl: "images/ginkgo.jpg",
  },
  {
    id: 139,
    name: "Bacopa Monnieri",
    slug: "bacopa-monnieri",
    category: "Nootropics",
    primaryGoal: "Memory Formation",
    description:
      "Ayurvedic herb shown to improve memory retention and learning rates over long-term supplementation.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "300mg (Standardized extract)",
    timing: "With meals (fat soluble)",
    tags: ["Memory", "Anxiety", "Brain"],
    warnings: ["May cause stomach cramps"],
    imageUrl: "images/bacopa.jpg",
  },
  {
    id: 140,
    name: "Tongkat Ali",
    slug: "tongkat-ali",
    category: "Hormones",
    primaryGoal: "Testosterone Support",
    description:
      "Herb widely used to support free testosterone levels, libido, and stress reduction.",
    evidenceLevel: "B",
    evidenceLabel: "Medium/High",
    dosage: "200-400mg",
    timing: "Morning",
    tags: ["Testosterone", "Libido", "Stress"],
    warnings: ["Watch for purity/heavy metals"],
    imageUrl: "images/tongkat.jpg",
  },
  {
    id: 141,
    name: "Alpha-GPC",
    slug: "alpha-gpc",
    category: "Nootropics",
    primaryGoal: "Power Output and Focus",
    description:
      "Highly bioavailable choline source that crosses the blood-brain barrier. Increases acetylcholine and growth hormone output.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "300-600mg",
    timing: "60 min pre-workout",
    tags: ["Focus", "Power", "Brain"],
    warnings: [],
    imageUrl: "images/alphagpc.jpg",
  },
  {
    id: 142,
    name: "HMB",
    slug: "hmb",
    category: "Physical Performance",
    primaryGoal: "Muscle Preservation",
    description:
      "Metabolite of Leucine. Most effective for preventing muscle breakdown in beginners or during caloric deficits.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "3g",
    timing: "Split throughout the day",
    tags: ["Muscle", "Anti-Catabolic"],
    warnings: [],
    imageUrl: "images/hmb.jpg",
  },
  {
    id: 143,
    name: "ZMA",
    slug: "zma",
    category: "Recovery",
    primaryGoal: "Sleep and Recovery",
    description:
      "Patented blend of Zinc, Magnesium, and Vitamin B6. Supports recovery and sleep quality in athletes.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "1 serving (usually 3 caps)",
    timing: "Before bed (empty stomach)",
    tags: ["Sleep", "Recovery", "Testosterone"],
    warnings: ["Avoid taking with dairy"],
    imageUrl: "images/zma.jpg",
  },
  {
    id: 144,
    name: "EAAs (Essential Amino Acids)",
    slug: "eaa",
    category: "Physical Performance",
    primaryGoal: "Muscle Protein Synthesis",
    description:
      "Contains all 9 essential amino acids necessary for muscle building. More complete than BCAAs.",
    evidenceLevel: "A",
    evidenceLabel: "High",
    dosage: "10-15g",
    timing: "Intra or Post-workout",
    tags: ["Muscle", "Recovery"],
    warnings: [],
    imageUrl: "images/eaa.jpg",
  },
  {
    id: 145,
    name: "Selenium",
    slug: "selenium",
    category: "Minerals",
    primaryGoal: "Thyroid Health",
    description:
      "Trace mineral essential for thyroid hormone metabolism and antioxidant defense (glutathione peroxidase).",
    evidenceLevel: "A",
    evidenceLabel: "Very High",
    dosage: "55-200mcg",
    timing: "Morning",
    tags: ["Thyroid", "Immunity"],
    warnings: ["Toxic in high doses (>400mcg)"],
    imageUrl: "images/selenium.jpg",
  },
  {
    id: 146,
    name: "Biotin (Vitamin B7)",
    slug: "biotin",
    category: "Beauty",
    primaryGoal: "Hair and Nail Health",
    description:
      "B-vitamin often used to strengthen brittle nails and support hair growth.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "2500-5000mcg",
    timing: "With meals",
    tags: ["Hair", "Nails", "Skin"],
    warnings: ["Can interfere with thyroid lab tests"],
    imageUrl: "images/biotin.jpg",
  },
  {
    id: 147,
    name: "Resveratrol",
    slug: "resveratrol",
    category: "General Health",
    primaryGoal: "Longevity",
    description:
      "Compound found in red wine/grapes. Activates sirtuins which are associated with anti-aging and heart health.",
    evidenceLevel: "C",
    evidenceLabel: "Controversial (Human data limited)",
    dosage: "150-500mg (Trans-Resveratrol)",
    timing: "Morning with fat",
    tags: ["Anti-aging", "Heart"],
    warnings: [],
    imageUrl: "images/resveratrol.jpg",
  },
  {
    id: 148,
    name: "Astaxanthin",
    slug: "astaxanthin",
    category: "General Health",
    primaryGoal: "Antioxidant / Skin Protection",
    description:
      "Powerful carotenoid that improves skin elasticity, eye health, and protects against UV damage.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "4-12mg",
    timing: "With meals containing fat",
    tags: ["Skin", "Eyes", "Antioxidant"],
    warnings: [],
    imageUrl: "images/astaxanthin.jpg",
  },
  {
    id: 149,
    name: "Quercetin",
    slug: "quercetin",
    category: "General Health",
    primaryGoal: "Immunity and Allergy Relief",
    description:
      "Flavonoid with anti-inflammatory and antihistamine properties. Often combined with Zinc or Bromelain.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "500-1000mg",
    timing: "Daily",
    tags: ["Immunity", "Allergies", "Inflammation"],
    warnings: [],
    imageUrl: "images/quercetin.jpg",
  },
  {
    id: 150,
    name: "Alpha Lipoic Acid (ALA)",
    slug: "ala",
    category: "General Health",
    primaryGoal: "Antioxidant / Insulin Sensitivity",
    description:
      "Universal antioxidant (water and fat soluble) that helps regenerate other antioxidants and improves glucose uptake.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "300-600mg",
    timing: "Before meals",
    tags: ["Glucose", "Nerves", "Antioxidant"],
    warnings: [],
    imageUrl: "images/ala.jpg",
  },
  {
    id: 151,
    name: "Betaine Anhydrous",
    slug: "betaine",
    category: "Physical Performance",
    primaryGoal: "Power and Hydration",
    description:
      "Also known as Trimethylglycine. Improves power output and cellular hydration. Reduces homocysteine levels.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "2.5g",
    timing: "Pre-workout",
    tags: ["Power", "Strength", "Heart"],
    warnings: [],
    imageUrl: "images/betaine.jpg",
  },
  {
    id: 152,
    name: "Digestive Enzymes",
    slug: "digestive-enzymes",
    category: "Digestion",
    primaryGoal: "Nutrient Absorption",
    description:
      "Blend of enzymes (Amylase, Protease, Lipase) to help break down food and reduce bloating.",
    evidenceLevel: "B",
    evidenceLabel: "High (Situation dependent)",
    dosage: "1 capsule",
    timing: "With large meals",
    tags: ["Digestion", "Bloating", "Gut"],
    warnings: [],
    imageUrl: "images/enzymes.jpg",
  },
  {
    id: 153,
    name: "MCT Oil",
    slug: "mct-oil",
    category: "Energy",
    primaryGoal: "Quick Energy",
    description:
      "Medium-Chain Triglycerides. Rapidly converted into ketones for instant energy. Popular in Keto diets.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "5-15ml",
    timing: "Morning or Pre-workout",
    tags: ["Energy", "Keto", "Brain"],
    warnings: ["Start small to avoid diarrhea"],
    imageUrl: "images/mct.jpg",
  },
  {
    id: 154,
    name: "Saw Palmetto",
    slug: "saw-palmetto",
    category: "Men's Health",
    primaryGoal: "Prostate Health",
    description:
      "Berry extract commonly used to decrease symptoms of an enlarged prostate (BPH).",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "320mg",
    timing: "Daily",
    tags: ["Prostate", "Hair Loss"],
    warnings: [],
    imageUrl: "images/sawpalmetto.jpg",
  },
  {
    id: 155,
    name: "Fenugreek",
    slug: "fenugreek",
    category: "Libido",
    primaryGoal: "Libido and Glucose",
    description:
      "Herb shown to boost libido and help regulate blood sugar levels. Often present in testosterone boosters.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "500-600mg",
    timing: "With meals",
    tags: ["Libido", "Glucose", "Lactation"],
    warnings: ["Maple syrup smell in sweat"],
    imageUrl: "images/fenugreek.jpg",
  },
  {
    id: 156,
    name: "Garlic Extract (Aged)",
    slug: "garlic-extract",
    category: "Heart Health",
    primaryGoal: "Blood Pressure and Immunity",
    description:
      "Provides cardiovascular benefits, reducing blood pressure and arterial stiffness. Potent immune booster.",
    evidenceLevel: "A",
    evidenceLabel: "Very High",
    dosage: "600-1200mg",
    timing: "With meals",
    tags: ["Heart", "Blood Pressure", "Immunity"],
    warnings: ["Blood thinning effect"],
    imageUrl: "images/garlic.jpg",
  },
  {
    id: 157,
    name: "Ginger Root",
    slug: "ginger",
    category: "Digestion",
    primaryGoal: "Nausea and Inflammation",
    description:
      "Highly effective for treating nausea and reducing muscle pain/soreness due to anti-inflammatory properties.",
    evidenceLevel: "A",
    evidenceLabel: "Very High",
    dosage: "1-2g",
    timing: "As needed or daily",
    tags: ["Digestion", "Nausea", "Joints"],
    warnings: ["Heartburn at high doses"],
    imageUrl: "images/ginger.jpg",
  },
  {
    id: 158,
    name: "5-HTP",
    slug: "5-htp",
    category: "Mood/Sleep",
    primaryGoal: "Serotonin Production",
    description:
      "Direct precursor to serotonin. Used to improve mood and sleep. Should not be mixed with antidepressants.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "50-200mg",
    timing: "Evening",
    tags: ["Mood", "Sleep", "Appetite"],
    warnings: ["Do not use with SSRIs"],
    imageUrl: "images/5htp.jpg",
  },
  {
    id: 159,
    name: "Yohimbine",
    slug: "yohimbine",
    category: "Stimulants",
    primaryGoal: "Stubborn Fat Loss",
    description:
      "Alpha-2 adrenergic antagonist. Helps mobilize fat from stubborn areas. Potent stimulant.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "0.2mg/kg bodyweight",
    timing: "Fasted cardio only",
    tags: ["Fat Loss", "Energy"],
    warnings: ["Causes anxiety/jitters", "Raises heart rate"],
    imageUrl: "images/yohimbine.jpg",
  },
  {
    id: 160,
    name: "Green Tea Extract (EGCG)",
    slug: "green-tea-extract",
    category: "Fat Loss",
    primaryGoal: "Metabolism Support",
    description:
      "Rich in catechins (EGCG) which can slightly increase fat oxidation and provide antioxidant benefits.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "400-500mg EGCG",
    timing: "Before workout",
    tags: ["Fat Loss", "Antioxidant"],
    warnings: ["Do not take on empty stomach (nausea)"],
    imageUrl: "images/greentea.jpg",
  },
  {
    id: 161,
    name: "Boron",
    slug: "boron",
    category: "Minerals",
    primaryGoal: "Free Testosterone and Bones",
    description:
      "Trace mineral that reduces SHBG, thereby increasing Free Testosterone levels. Also vital for bone density.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "3-10mg",
    timing: "Morning",
    tags: ["Testosterone", "Bones"],
    warnings: [],
    imageUrl: "images/boron.jpg",
  },
  {
    id: 162,
    name: "Holy Basil (Tulsi)",
    slug: "holy-basil",
    category: "Adaptogens",
    primaryGoal: "Stress and Anxiety",
    description:
      "Sacred herb in Ayurveda used to reduce metabolic and psychological stress.",
    evidenceLevel: "C",
    evidenceLabel: "Medium",
    dosage: "500mg",
    timing: "Daily",
    tags: ["Stress", "Immunity"],
    warnings: [],
    imageUrl: "images/tulsi.jpg",
  },
  {
    id: 163,
    name: "Phosphatidylserine",
    slug: "phosphatidylserine",
    category: "Stress/Cognition",
    primaryGoal: "Cortisol Reduction",
    description:
      "Phospholipid that helps blunt the cortisol response to exercise and stress. Supports memory in elderly.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "400-800mg",
    timing: "Post-workout or Evening",
    tags: ["Cortisol", "Memory", "Stress"],
    warnings: [],
    imageUrl: "images/phosphatidylserine.jpg",
  },
  {
    id: 164,
    name: "Spirulina",
    slug: "spirulina",
    category: "Superfoods",
    primaryGoal: "Nutrient Density",
    description:
      "Blue-green algae rich in protein, vitamins, and antioxidants. effective for allergic rhinitis.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "1-3g",
    timing: "Any time",
    tags: ["Detox", "Allergies", "Antioxidant"],
    warnings: ["Source quality matters"],
    imageUrl: "images/spirulina.jpg",
  },
  {
    id: 165,
    name: "Chlorella",
    slug: "chlorella",
    category: "Superfoods",
    primaryGoal: "Detoxification",
    description:
      "Freshwater algae known for binding to heavy metals and aiding in detoxification.",
    evidenceLevel: "C",
    evidenceLabel: "Medium",
    dosage: "2-3g",
    timing: "Any time",
    tags: ["Detox", "Immunity"],
    warnings: [],
    imageUrl: "images/chlorella.jpg",
  },
  {
    id: 166,
    name: "Huperzine A",
    slug: "huperzine-a",
    category: "Nootropics",
    primaryGoal: "Focus and Learning",
    description:
      "Inhibits the breakdown of acetylcholine, the 'learning neurotransmitter'. Very potent.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "50-200mcg",
    timing: "Pre-study/work",
    tags: ["Focus", "Memory"],
    warnings: ["Cycle needed (tolerance)"],
    imageUrl: "images/huperzine.jpg",
  },
  {
    id: 167,
    name: "Tart Cherry Extract",
    slug: "tart-cherry",
    category: "Recovery",
    primaryGoal: "Uric Acid and Sleep",
    description:
      "Reduces uric acid levels (gout) and improves sleep due to natural melatonin content.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "500mg extract or juice",
    timing: "Evening",
    tags: ["Recovery", "Sleep", "Gout"],
    warnings: [],
    imageUrl: "images/tartcherry.jpg",
  },
  {
    id: 168,
    name: "L-Arginine",
    slug: "l-arginine",
    category: "Physical Performance",
    primaryGoal: "Blood Flow",
    description:
      "Precursor to Nitric Oxide. While Citrulline is more effective, Arginine is still widely used for circulation.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "3-6g",
    timing: "Pre-workout",
    tags: ["Pump", "Circulation"],
    warnings: ["Can cause GI distress"],
    imageUrl: "images/arginine.jpg",
  },
  {
    id: 169,
    name: "Chromium Picolinate",
    slug: "chromium",
    category: "Minerals",
    primaryGoal: "Blood Sugar Management",
    description:
      "Trace mineral that enhances the action of insulin. Useful for carbohydrate metabolism.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "200-1000mcg",
    timing: "With carbohydrate meals",
    tags: ["Glucose", "Insulin"],
    warnings: [],
    imageUrl: "images/chromium.jpg",
  },
  {
    id: 170,
    name: "Glycerol",
    slug: "glycerol",
    category: "Physical Performance",
    primaryGoal: "Hyper-Hydration",
    description:
      "Draws water into muscle cells, creating massive pumps and preventing dehydration during endurance events.",
    evidenceLevel: "B",
    evidenceLabel: "High",
    dosage: "2-5g",
    timing: "Pre-workout with lots of water",
    tags: ["Pump", "Hydration", "Endurance"],
    warnings: ["Clumps easily in powder"],
    imageUrl: "images/glycerol.jpg",
  },
  {
    id: 171,
    name: "Vitamin E",
    slug: "vitamin-e",
    category: "Vitamins",
    primaryGoal: "Oxidative Stress",
    description:
      "Fat-soluble antioxidant. Protects cell membranes from oxidative damage.",
    evidenceLevel: "A",
    evidenceLabel: "High",
    dosage: "15mg (approx 22 IU)",
    timing: "With meals",
    tags: ["Skin", "Antioxidant"],
    warnings: ["Do not overdose"],
    imageUrl: "images/vitamine.jpg",
  },
  {
    id: 172,
    name: "Potassium Citrate",
    slug: "potassium",
    category: "Minerals",
    primaryGoal: "Electrolyte Balance",
    description:
      "Crucial for muscle contraction and regulating blood pressure. Often lacking in modern diets.",
    evidenceLevel: "A",
    evidenceLabel: "Very High",
    dosage: "Dependent on diet",
    timing: "With food",
    tags: ["Cramps", "Blood Pressure", "Hydration"],
    warnings: ["Dangerous if overdosed"],
    imageUrl: "images/potassium.jpg",
  },
  {
    id: 173,
    name: "Valerian Root",
    slug: "valerian",
    category: "Sleep",
    primaryGoal: "Insomnia Relief",
    description:
      "Herbal sedative used for centuries to treat insomnia and anxiety.",
    evidenceLevel: "B",
    evidenceLabel: "Medium",
    dosage: "300-600mg",
    timing: "30 min before bed",
    tags: ["Sleep", "Relaxation"],
    warnings: ["Strong earthy smell"],
    imageUrl: "images/valerian.jpg",
  },
  {
    id: 174,
    name: "Calcium Citrate",
    slug: "calcium",
    category: "Minerals",
    primaryGoal: "Bone Density",
    description:
      "Essential for bone structure and muscle contraction. Citrate form is absorbed well even without food.",
    evidenceLevel: "A",
    evidenceLabel: "Very High",
    dosage: "500-1000mg",
    timing: "Divided doses",
    tags: ["Bones", "Muscles"],
    warnings: ["Risk of kidney stones if too high"],
    imageUrl: "images/calcium.jpg",
  },
  {
    id: 175,
    name: "St. John's Wort",
    slug: "st-johns-wort",
    category: "Mood",
    primaryGoal: "Mild Depression",
    description:
      "Herbal remedy comparable to prescription antidepressants for mild depression.",
    evidenceLevel: "A",
    evidenceLabel: "High",
    dosage: "300mg (3x daily)",
    timing: "With meals",
    tags: ["Mood", "Depression"],
    warnings: ["VERY high drug interaction risk", "Photosensitivity"],
    imageUrl: "images/stjohnswort.jpg",
  },
  {
    id: 176,
    name: "CLA (Conjugated Linoleic Acid)",
    slug: "cla",
    category: "Fat Loss",
    primaryGoal: "Body Composition",
    description:
      "Fatty acid found in meat and dairy. Popular for weight loss, though human studies are mixed.",
    evidenceLevel: "C",
    evidenceLabel: "Low/Controversial",
    dosage: "3-6g",
    timing: "With meals",
    tags: ["Fat Loss", "Metabolism"],
    warnings: [],
    imageUrl: "images/cla.jpg",
  },
  {
    id: 177,
    name: "D-Aspartic Acid (DAA)",
    slug: "daa",
    category: "Hormones",
    primaryGoal: "Temporary Testosterone Boost",
    description:
      "Amino acid regulator of testosterone synthesis. Provides a short-term spike (1-2 weeks) then returns to baseline.",
    evidenceLevel: "C",
    evidenceLabel: "Low (Short term only)",
    dosage: "3g",
    timing: "Morning",
    tags: ["Testosterone", "Fertility"],
    warnings: ["Effect is temporary"],
    imageUrl: "images/daa.jpg",
  },
];
